version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - /mnt/c/docker/postgres_data:/var/lib/postgresql/data
  webapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/docker/webapp_data:/app
